### ISSUE TITLE
Codelists for use across multiple apps

### ISSUE THREAD

**Issue by GGunnar** [Altinn/app-lib-dotnet#143]
## Description
Codelists that are only relevant for a single app are already handled.

Static codelists could just be delivered from our CDN (as per comment by @altinnadmin below)

But is there a need for centralised dynamic codelists hosted by Altinn (rather than available from the original data source through an API)?

## In scope
- [ ] Detailing of how to offer static codelists
- [ ] Market check for need for dynamic codelists

## Out of scope
> What's **out** of scope for this analysis?

Development in MVP3.

## Constraints
> Constraints or requirements (technical or functional) that affects this analysis.

Lorem ipsum

## Analysis

Lorem ipsum

## Conclusion
> Short summary of the proposed solution.

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by altinnadmin** [comment]
Codelists as a concept might be outdated. This could be solved by CDN (for static json lists) and by creating apps with API (for dynamic code lists).

**Comment by FinnurO** [comment]
Altinn/altinn-studio#7924

**Comment by elenagustafsson** [comment]
Det bør være selvfølge at man skal kunne bruke samme kodeliste på tvers av apper. F.eks. om vi har 100 skjema som inneholder kommuneliste så må det kunne brukes samme kodeliste som ligger "utenfor" appene, og om det er endring i kodelisten så skal man ikke måtte gjennomføre samme endring i samtlige skjema. Altså slik det er i dag i Altinn II.

**Comment by andersrodahl-brreg** [comment]
I skjemaet brg/rrh-innrapportering for Brønnøysundregistrene har vi i dag en landkodeliste som ligger som en del av appen. Hvis alle apper gjør tilsvarende får vi en vedlikeholds-utfordring på sikt, og det blir stor fare for at de forskjellige kodelistene rundt omkring ikke er i sync. Denne typen kodelister burde vært felles på tvers av alle apper. Vi bruker Alpha3-landkoder i vår kodeliste, men man må sikkert støtte både Alpha2- og Alpha3-landkoder. Ellers bør man håndtere utgåtte koder på ett eller annet vis. Vårt skjema har preutfylling, noe som i verste fall kan bety at det kommer en utgått landkode i prefilldataene, og da må det være mulig å vise data i skjemaet selv om en landkode evt er markert som utgått"
