### ISSUE TITLE
Support new PDF service in app lib nugets

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#153]
### Description

The new pdf service is based on chromium

### Additional Information

Epic: https://github.com/Altinn/app-lib-dotnet/issues/63

### Tasks

- [x] Expose new api for frontend to call where we check if there is any custom logic to hide components from PDF (IPdfFormatter). The api should return an object with two lists (pages and components) including the id of the components to be hidden from PDF. #157 
- [x] Call the new PDF service from within the app lib code. Should be possible to feature toggle on/off
- [x] Implement a new PDF client

### Acceptance Criterias

- [x] One PDF generated per datamodel (if more than one)
- [x] It should be easy to disable PDF generation

**Comment by ivarne** [comment]
Do we really want to keep the old “hide component in pdf” logic for the new pdf generator. This new api will require updating of the nuggets anyway, so we have the option to just remove the interface instead.

**Comment by bjosttveit** [comment]
We could remove it, but keeping it makes it easier for existing apps to adopt the new PDF service. It also provides a dynamic way of specifying excluded pages/components as opposed to `Settings.json` which is completely static.

**Comment by RonnyB71** [comment]
Valid question. I'm not sure if we can remove it, we need to make sure we actually cover how this interface has been used in various apps. I imagine you could have some rules for hiding that we don't support directly with the new solution.
