### ISSUE TITLE
Extended attachment validation

### ISSUE THREAD

**Issue by ghost** [Altinn/app-lib-dotnet#156]
### Description
We want to be able to access the metadata about the file and the file as a stream, when the file is uploaded.
The information should be sent as soon as the file is uploaded in the app, so that it is possible to send validation feedback to the client. 

**Validation examples**
* Validate that the file's MIME type is what the extension and content-type claims the file to be
* Image resolution is too low based on the files metadata
* PDF is allowed, but not version 1.5 is this might contain executable scripts

### Additional Information
Checking a file's mime type based on it's binary data is based on analyzing the byte stream for known signatures. We should look into using a library for this. One alternative is for .Net is https://github.com/MediatedCommunications/Mime-Detective

File sizes might be large ie. in the 50 MB to 200 MB range. 

### Tasks
- [x] Identify library to sniff for MIME type

### Acceptance Criterias
- [x] Validate the actual MIME type of the file should be a standard solution enabled with configuration
- [x] The solution should allow for metadata parsers for known file types to be added by registering an implementation of a defined interface, if no metadata parsers exists the minimum metadata available should be the MIME type (if identified)
- [x] Metadata should be added to a context object as name value/pairs making it possible to add validations against them eg. the MIME type should be image/png AND the width should be more than 2000 and the height more than 1500.
- [ ] Validation messages should be localized into the appropriate language and support text resources
