### ISSUE TITLE
Automate publishing of nugets

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-lib-dotnet#2]
### Description

 The release process of these packages should be changed to:
* [create a GitHub release](https://docs.github.com/en/repositories/releasing-projects-on-github/automation-for-release-forms-with-query-parameters) including
    * release notes based on PR's since last release ref. https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
    * release assets (nuget)
    * link to package on nuget.org
* automatically produce new nuget packages when a given tag/release is created for example **v5.1.0** or **v5.1.0-alpha.1** 

This chore is the continuation of the issue: https://github.com/Altinn/app-template-dotnet/issues/87

### Tasks

- [ ] Update csproj files to support automatic release based on a tag/release in github
- [ ] Create workflow for publishing new nugets

### Acceptance Criterias

- [ ] Doc is updated to reflect the changes
- [ ] AltinnPedia is updated to reflect the changes (deploy of nuget packages)
- [ ] New versions of nugets are published when a new Release is created on github
- [ ] Pipeline should include alpha packages and create packages created from branches
