### ISSUE TITLE
Create signing document

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#206]
### Description

As part of a user performing a signing action we should log a specific signature document capturing the action as well as linking it to the data it is signing of on. The signature document should be captured for both a positive signature and a negative signature ie. the signee refused to sign.

### Additional Information

Related epic: https://github.com/Altinn/app-template-dotnet/issues/170

### Tasks

- [ ] Capture a positive signature
- [ ] Capture a negative signature

### Acceptance Criterias

- [ ] Signature documents is captured and stored as a specific datatype
- [ ] Backend should validate that the current step requires a signature and that the current logged on user has access to perform that action
