### ISSUE TITLE
Implement new expressions from frontend in backend

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-lib-dotnet#276]
### Description

Frontend has implemented a set of new functions https://github.com/Altinn/app-frontend-react/issues/1176.

We need to implement the same functions in backend so evaluation of expressions still function the same frontend and backend for those functions that are regarded as common for both frontend and backend.

### Tasks

- [ ] syncronize shared-tests folder
- [ ] add new folders to test fictures
- [ ] implement missing functions

### Acceptance Criterias

- [ ] all tests run green

**Comment by RonnyB71** [comment]
Update documentation to reflect what's supported on the backend ref. https://docs.altinn.studio/app/development/logic/expressions/
