### ISSUE TITLE
As an end user I want to receive a receipt by e-mail

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-lib-dotnet#320]
## Description
As an end user I want to receive a receipt by email after submitting a form.

Specification and sketch of the receipt page itself can be found in epic Altinn/altinn-studio#1050 

This issue should also handle "videresend e-post" when you enter the receipt page from Altinn inbox. 
Altinn/altinn-studio#926 
## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
Input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
- What is allowed/not allowed (negative tesing)
- Validations
- Error messages and warnings
- ...

## Tasks
- [ ] Specify what the e-mail receipt should contain
- [ ] Design e-mail receipt
- [ ] Implement e-mail functionality
- [ ] Documentation (if relevant)
- [ ] Test / QA (if relevant)

**Comment by RonnyB71** [comment]
Closing this as this points to the receipt displayed from the inbox and this should be solved as part of "arbeidsflate" for Dialogporten.
