### ISSUE TITLE
Enable Nullable reference types on Altinn.App.Api

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#326]
### Description

Nullable reference types is a great way to reduce the chance of unexpected null pointer exceptions and a great tool to help improve code quality by checking for null references only where it makes sense.

### Tasks

- [ ] Add `<Nullable>enable</Nullable>` in `Altinn.App.Api.csproj`
- [ ] Remove all `#nullable enable` declarations in the files that have them.
- [ ] Fix all warnings (and tests)
- [ ] Go through all public apis and make sure that the change in behaviour makes sense (Eg: `[FromQuery]` parameters that wasn't nullable, are now required (Fx the `language` parameter in `OptionsController`))
