### ISSUE TITLE
Remove deprecated backend features

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#336]
### Description

Do a little cleanup of app-lib-dotnet to remove remnants of things that isn't used anymore

### Tasks

- [ ] No support for apps without layout sets 
- [x] Remove `IPageOrder` (pageOrderController needs to return the old default for v3, but not customisable)
- [x] https://github.com/Altinn/app-lib-dotnet/issues/415

**Comment by tjololo** [comment]
Should we keep support for non layoutsets in v8 as we support v3 of frontend?
Removing IPageOrder seems like something we should do

**Comment by ivarne** [comment]
> Should we keep support for non layoutsets in v8 as we support v3 of frontend?

We don't need them in v3, so that is an independent decision. If the upgrade tool moves the files, I think it makes sense to remove the APIs

> Removing IPageOrder seems like something we should do

If the upgrade tool works and fixes all apps: Absolutely yes! (otherwise I'm not sure)
