### ISSUE TITLE
Support servicetask in application process

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#368]
### Description

Currently we do not support service tasks in the application process. Although we do perform tasks as part of the process that could have been solved as a service task, for example generating a PDF. Today the PDF generation is done as part of a exiting a data task. This means that the job of generating a PDF is not visible in the process diagram, nor is it possible to postpone it until all data tasks (if you have multiple) are done and generate one PDF at the end.

### Additional Information

The definition of a Service Task as defined in [the BPMN 2.0 Spec](https://www.omg.org/spec/BPMN/2.0/PDF).

**Service Task**
A Service Task is a Task that uses some sort of service, which could be a Web service or an automated application.

### Tasks

- [x] Take the current PDF generation, extract it from the process and expose it as a script/service task.
- [ ] Update convert tool to add a PDF task after any data tasks in order to maintain the process as is.

### Acceptance Criterias

- [ ] It is possible to add a new PDF task type to the process which triggers the PDF generation code as-is today.
- [ ] It should be possible to add multiple PDF tasks, including chaining them, in the processes
- [ ] The process engine should automatically execute the PDF task and move the process to the next step

**Comment by tjololo** [comment]
We also need to think about how we handle errors inside a service task.
Should we rollback to the previous step implicitly or should we require the developer to define a error boundary event with a clear path of where to go if the service task failed. Or the always popular: "both please"
Both please would "rollback" to previous task if no boundary event is defined.

**Comment by RonnyB71** [comment]
On the topic of error handling consider https://github.com/Altinn/app-lib-dotnet/issues/171 and https://github.com/Altinn/app-lib-dotnet/issues/19
