### ISSUE TITLE
Brukerbetaling av en Altinn 3 tjeneste

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#399]
### Description

Analyse av veikart oppgave https://github.com/digdir/roadmap/issues/80

### In scope
* Betalingsfunksjonalitet tilsvarende det som finnes på Altinn 2 i dag
* Støtte for Nets i første omgang

### Out of scope
* Støtte for ulike betalingsleverandører (Nets, DIBS, Payex)

### Additional Information
Dokumentasjon fra Nets: https://developer.nexigroup.com/nexi-checkout/en-EU/docs/

### Tasks

- [x] Write ITask implementation  for Signing datatype
- [x] Write ITask  implementation for Payment dataype
- [x] Altinn/app-lib-dotnet#400
- [x] Hook nets code into process code (might need further analysis/refinement)
- [x] Altinn/app-lib-dotnet#401
- [ ] Test/debug backend code and hand over to frontend
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/485
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/486
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/487
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/488
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/491
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/499
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/500
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/501
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/502
```

**Comment by olavflar** [comment]
Oversikt / Sammendrag:
![Skjermbilde 2023-11-07 kl  13 09 21](https://github.com/Altinn/app-template-dotnet/assets/70377508/58a0f019-92a0-4bd2-81d5-3c240d581a4b)

Blir sendt ut til betalingsleverandør - de fleste bruker nets i dagens løsning:

![Skjermbilde 2023-11-07 kl  13 09 26](https://github.com/Altinn/app-template-dotnet/assets/70377508/2bd8e467-509f-4843-8b40-8f8da142ba2f)

Feilmelding:
![Skjermbilde 2023-11-07 kl  13 09 31](https://github.com/Altinn/app-template-dotnet/assets/70377508/00fca703-0a86-4218-ab67-72ce6620b855)

Kvittering:
![Skjermbilde 2023-11-07 kl  13 14 13](https://github.com/Altinn/app-template-dotnet/assets/70377508/841d0f37-4489-4b57-892e-05891b8867c2)

**Comment by tjololo** [comment]
Trying to gather a list of duplicate issues created so we hopefully can close the others and defragment the information.
* https://github.com/Altinn/app-template-dotnet/issues/15
* https://github.com/Altinn/app-lib-dotnet/issues/334

**Comment by bjorntore** [comment]
Doing rest of payment work in smaller tasks.
