### ISSUE TITLE
Events endpoint in application

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#47]
### Description

The application needs a generic events endpoint where the Events system kan POST events that the application has subscribed to including "note-to-self" events.

### Tasks

- [x] Create an authorized endpoint to which the Events system kan POST events the application has subscribed to
- [x] Create a way to register and inject classes handling the various events - one class per event type

### Acceptance Criterias
- [x] The generic events endpoint is exposed at: `{org}/{app}/api/v1/eventsreceiver`
- [x] The endpoint does not allow anonymous calls and authorizes the event system
- [x] The endpoint returns 425 Too early in the case where the event cannot be processed as intended
- [x] The endpoint return 500 Server error in the case where an unhandled exception occurs
- [x] The endpoint identifies the handling class based on the event type received
