### ISSUE TITLE
Register event subscription in app

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#49]
### Description

The application needs to be able to subscribe to "note-to-selv" events during startup ie. evnts that the app itself creates to remind itself to check the status on previous external message deliveries. Technically any type of event should be possible to subscribe to.

### Tasks

- [x] Add support for subscribing to a custom "note-to-self" event on application start or basically any type of custom event from the app.

### Acceptance Criterias
- [x] The subscription is successfully registered in the event system
- [x] The app is authenticated as it self towards the event system
