### ISSUE TITLE
Implement SMS support for app developers

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#493]
### Description

As an application developer I would like to have support for sending SMS from an Altinn 3 app in order to support notifications as part of the process.

### Additional Information

Team Core have implemented a [Notification service](https://github.com/Altinn/altinn-notifications) with a endpoint for sending SMS.

See [related issue for e-mail](https://github.com/Altinn/app-lib-dotnet/issues/494)

### Tasks

- [x] Implement a client to talk to the SMS api
- [x] Implement localtest setup to use locally

### Acceptance Criterias

- [x] How to use from within a application is documented
- [x] The logic is made available to the application developers as a injectable service
