### ISSUE TITLE
Implement e-mail support for app developers

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#494]
### Description

As an application developer I would like to have support for sending e-mails from an Altinn 3 app in order to support e-mail notifications as part of the process. 

### Additional Information

Team Core have implemented a [Notification service](https://github.com/Altinn/altinn-notifications) with a endpoint for sending e-mails.

See [related issue for SMS](https://github.com/Altinn/app-lib-dotnet/issues/493)

### Tasks

- [x] Implement a client to talk to the e-mail api

### Acceptance Criterias

- [x] How to use from within a application is documented
- [x] The logic is made available to the application developers as a injectable service
