### ISSUE TITLE
Eformidling hardening

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-lib-dotnet#50]
### Description

Due to the lack of support for external asynchronous message patterns in Altinn 3, the current App integration with Eformidling stand the risk of loosing information about failing messages. In other words if Eformidling fails to deliver the message to KS for some reason the app will currently not receive this information.

This epic addresses this issue using a generic re-usable asynchronous pattern.

### In scope

- [x] Upgrade the application in question to v7
- [x] Implement the changes needed to handle external asynchronous message delivery
- [x] Error handling in the case of either the delivery to the external message system or Events fails. These two should be handled as one operation - ie. they succeed together or they fail together.
- [x] Implement the changes in the application in question
- [ ] Generate a new  "shipment" id when sending data to eFormidling. We're currently using instance id which might cause retry to be rejected by eFormidling. Shipment id as instance id is used to identify the instance meaning we need to add the instance id so it gets sent back on the reminder event.
- [x] Testing and verification
- [x] Events will need to prevent the creation of duplicate subscription registrations. [issue](https://github.com/Altinn/altinn-events/issues/129).
- [x] Documentation

### Issues
- [x] #47 
- [x] #48 
- [x] #49 

### Additional Information

[Sequence diagram](https://github.com/Altinn/altinn-studio/files/9596838/eFormidling-App.pdf)

The implementation should be done on v7 of the app template, meaning applications using this will need to be on this version.

**Textual description of the solution (in Norwegian) by @SandGrainOne:**

> Alle apps som ønsker å sende data gjennom eFormidling må ha prosesssteget feedback i sin prosess. Steget skal brukes til å vise sluttbruker at dataene blir sent til riktig kommune og at vi venter på svar. Det kan også bli aktuelt å vise en feilmelding skulle det oppstå problemer. Steget er i stand til å trigge page refresh ved jevne mellomrom. Bruker skal altså ikke gjøre noe på siden selv. Når forsendelsen er bekreftet sent vil refresh av siden føre brukeren automatisk til kvitteringssiden.
> 
> Appene må også utvides med et nytt API endepunkt som kan motta eventer som «pushes» ut fra Events komponenten. Når endepunktet blir kalt fra Events skal det gjøre et oppslag i eFormidling for å se om det har kommet inn noen kvitteringer knyttet til den aktuelle forsendelsen.  Kvitteringer undersøkes for å avgjøre om eFormidling har lyktes med å sende data videre til riktig mottaker. 
> 
> Hvis det ikke har kommet noen kvittering skal logikken svare Events komponenten med en statuskode som indikerer feil. Dette vil gjøre at Events komponenten vil forsøke igjen senere.  Hvis eFormidling melder om at forsendelsen er levert ok, så skal logikken i Appen oppdatere riktig instance med ny status. I praksis kalle på «process/next». Neste gang bruker sjekker sin instance vil de bli vist kvittering for at dataene er sent på samme måte som i dag. 
> 
> Appene må også registrere et Events abonnement hvor de angir sitt nye endepunkt som mottaker av Events. 
> 
> Når bruker er ferdig med å fylle ut skjema, skal Appen utføre to operasjoner. Den skal først sende dataene gjennom eFormidling og så skal den registrere en hendelse/event. Dette er da samme Event som den senere vil få tilbake på sitt eget API endepunkt. Formålet med å bruke Events komponenten er den innebygde retry-mekanismen. På denne måten slipper vi å implementere noen ny komponent nå i første omgang.
> 
> Har vedlagt et slags sekvensdiagram. (De som har negativ feedback bør ha sertifisering i UML.)
> 
> En ting vi ikke diskuterte like godt i går var hvordan det skulle håndteres hvis noe går galt. Hva om eFormidling etter 2 sekunder > sier at data ikke kan leveres? Slik det er tegnet nå vil Appen vise en feilmelding på feedback steget til evig tid. 
> 
> Det er flere ting som altså må lages i App.
> 
> 1.	Mekanisme for å registrere Events abonnement (ved oppstart?). Krever klient kode for å kommunisere med Events. 
> 2.	Nytt API endepunkt for å ta imot Events. 
> a.	Klientkode og logikk for å hente kvitteringer fra eFormidling og kunne tolke disse. 
> b.	Logikk for å oppdatere status på instance slik at den blir arkivert.
> c.	Logikk for å kvittere ut saken (complete) som behandlet på veiene av DiHE. 
> 3.	Nytt prosess steg. Vi håper vi kan bruke feedback steget. 
> 4.	Feilhåndtering…
