### ISSUE TITLE
Dependency changes for v9 tracking issue

### ISSUE THREAD

**Issue by martinothamar** [Altinn/app-lib-dotnet#647]
### Description

We need to cleanup package dependencies for v9

* [x] #507 was closed due to breaking change, will will replace this dependency with the ongoing work for automating Maskinporten integration
* [ ] #510 was closed due to `KeyVaultSettings` being removed. It is used by apps due to our `SecretsClient` and custom configuration of `KeyVaultClient` (both directly and transitively) from a deprecated package
* [ ] #539 was closed due to a deprecated package being used (through transitive dependency) in `SecretsClient`

The last two should be resolved/refactored together by providing a `SecretsClient` abstraction that works better and hides the implementation details. It should use the newser Azure SDKs including `Azure.Identity`.

Other dependencies which are deprecated and/or contain vulnerabilities need to be dealth with.

### Additional Information

![image](https://github.com/Altinn/app-lib-dotnet/assets/5425986/4994d087-0a14-4bc8-af78-2a6d9f96c490)

### Acceptance Criterias

- [ ] No dependencies with vulnerabilities
- [ ] No dependencies which are deprecated
- [ ] Fewer dependencies in general, to avoid churn
