### ISSUE TITLE
Parallel and Runtime Delegated Signing

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-lib-dotnet#793]
## Description

We need to support parallel signing, meaning multiple parties can sign in the same signing step.

We need support for delegating signing and reading rights to signees based on SSN+LastName or Org.nr, so that parties that don't have access to an instance through the policy file can be invited to sign something in Altinn.

## Consideration

- Requires instance delegation.
- Requires Correspondence integration in order to send a call-to-action message to the signees.

##  Acceptance criteria
- [ ] We are able to dynamically delegate access to read and sign the instance to people or organisations entered into the datamodel by someone with edit rights.
- [ ] We have a component for looking up a person based on SSN and Last name.
- [ ] We have a component for looking up a organisation based on organisation number.
- [ ] TE has a way of telling us where in the datamodel the signees we should delegate access to can be found.
- [ ] How TE can tell us where in the datamodel we can find the signees is documented. ISigneeProvider.
- [ ] Signees that get dynamically delegated access rights receive a message in their inbox with a link to the instance.
- [ ] Multiple parties can sign on the same signing task. Before it was max one signature per task.
- [ ] If the person that signs is not in the signee list, but has access because of the policy file, they also show up in the signee list after performing the sign action.
- [ ] The signing step supports default validation that requires all signees to sign.
- [ ] Default signing validation can be disabled.
- [ ] Default validation is documented.
- [ ] Custom validation of signatures can be implemented.
- [ ] Custom validation is documented.
- [ ] It's possible to setup "Reject" aka the ability to abort the signing step. Requires access rights to the "reject" action.
- [ ] If we fail to notify a signee that they should sign, it shows in the user interface with an error message.
- [ ] If we fail to delegate access to signee, it shows in the user interface. We should tell the user to retry?
- [ ] It's possible to generate a PDF of the signing step.
- [ ] It's possible to make a one-task app with only a signing step.
- [ ] It's possible to modify the layout and texts in a signing step.

## Rough preliminary technical sketch
![signing-proccess-technical-details drawio](https://github.com/user-attachments/assets/79a0d80b-b325-4ac2-8288-a8827d65c40b)

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/788
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/799
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/840
- [ ] https://github.com/Altinn/app-frontend-react/issues/2648
- [ ] https://github.com/Altinn/app-frontend-react/issues/2492
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/886
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/791
- [ ] https://github.com/Altinn/app-lib-dotnet/pull/945
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/965
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/790
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/136
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/803
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/869
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/953
- [ ] https://github.com/Altinn/app-frontend-react/issues/2799
- [ ] https://github.com/Altinn/app-frontend-react/issues/2801
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/789
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/1000
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/966
- [ ] https://github.com/Altinn/app-frontend-react/issues/2501
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/954
- [ ] https://github.com/Altinn/app-frontend-react/issues/2800
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/798
- [ ] https://github.com/Altinn/app-frontend-react/issues/2491
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/946
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/816
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/938
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/1013
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/801
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/969
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/806
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/805
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/795
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/865
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/882
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/968
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/970
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/1079
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/1105
```

**Tasks**
- [ ] Verify that this issue is labeled and written correctly (remove unused stuff, add missing stuff, verify tasks). DoP.
- [ ] Documentation (if relevant)
- [ ] Test / QA (if relevant)
