### ISSUE TITLE
Melding-integrasjon fra en Altinn app

### ISSUE THREAD

**Issue by martinothamar** [Altinn/app-lib-dotnet#820]
### Description

Meldingstjenesten brukes for å sende digital brev til andre parter.
Docs: https://docs.altinn.studio/correspondence/

Vi trenger en klient i app-bibliotek og automasjon for å gjøre brukerreisen god når man tar i bruk Altinn Melding inne i en Altinn app.

### In scope

Implementering av 
* `ICorrespondenceClient` i Altinn.App.Core
* Correspondence-støtte i localtest
* Maskinporten automasjon for `altinn:correspondence.write/read`

### Acceptance criteria

- [x] Altinn.App.Core har et interface som kan brukes til integrasjon med Melding
- [ ] Altinn k8s Operator har støtte for å generere innebygget/intern Maskinporten-klient som brukes for å understøtte integrerte features i en Altinn app
- [ ] Man kan skru på Altinn Melding som en feature for en app i Altinn Studio
- [ ] Localtest kan brukes for å teste ut interfacene i Altinn.App.Core lokalt
- [ ] Analyse/metrics/status av Meldings-integrasjon
