### ISSUE TITLE
Rename namespace `Altinn.App.Core.Features.FileAnalyzis`

### ISSUE THREAD

**Issue by danielskovli** [Altinn/app-lib-dotnet#856]
### Description

The namespace `Altinn.App.Core.Features.FileAnalyzis` is misspelled and should be changed to `Altinn.App.Core.Features.FileAnalysis`. The containing folder should also be renamed.

[Some files](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Features/FileAnalyzis/FileAnalysisResult.cs#L3) in the relevant folder have already taken this approach, but the result is that we now have two namespaces instead of one.

Consolidate this.

### Additional Information

The hard part that makes this breaking, is that apps might use these classes, and to make this change, we need an upgrade tool that automatically fixes app code.

### Tasks

- [ ] Rename folder
- [ ] Consolidate namespaces, removing the incorrect one
- [ ] Write appropriate migration instructions and/or automation script

### Acceptance Criterias

- [ ] The lib consumer has a single namespace available for "File Analysis" and it is spelled correctly in British English
